language: go
go:
  - 1.7
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - ./contrib/grab-headless_shell.sh $HOME/hs
script:
  - export CHROMEDP_NO_SANDBOX=true
  - export PATH=$PATH:$HOME/hs
  - go test -v -race -coverprofile=coverage.out
  - goveralls -service=travis-ci -coverprofile=coverage.out
