language: go
go:
  - 1.7
  - 1.8
  - tip
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install libstdc++6
  - go get github.com/mattn/goveralls
  - ./contrib/grab-headless_shell.sh $HOME/hs
script:
  - export PATH=$PATH:$HOME/hs
  - CHROMEDP_NO_SANDBOX=true go test -v -coverprofile=coverage.out
  - goveralls -service=travis-ci -coverprofile=coverage.out
