language: go
sudo: false
go:
  - 1.7
  - 1.8
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - ./contrib/grab-headless_shell.sh $HOME/hs
script:
  - export PATH=$PATH:$HOME/hs
  - GOMAXPROCS=1 CHROMEDP_NO_SANDBOX=true go test -race -coverprofile=coverage.out
  - goveralls -service=travis-ci -coverprofile=coverage.out
