on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        # We want testing.T.Cleanup for parallel subtests.
        # go-version: [1.13.x, 1.16.x]
        # TODO: Add macos-latest and windows-latest. The former doesn't come
        # with Chrome by default, and the latter needs lots of work in the tests.
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: TMPDIR=$RUNNER_TEMP go test -v ./...
  test-headless-shell:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: ./contrib/docker-test.sh
